#!/bin/bash
set -e

# Deploy CFE declaration to BIG-IP ${bigip_name}
# Generated by Terraform — do not edit manually

BIGIP_HOST="${bigip_mgmt_ip}"
BIGIP_PORT="${bigip_mgmt_port}"
BIGIP_USER="${bigip_username}"
BIGIP_PASS=$(terraform output -raw ${bigip_password_output})
CFE_FILE="$(dirname "$0")/${cfe_filename}"

echo "==> Deploying CFE to ${bigip_name} at $${BIGIP_HOST}:$${BIGIP_PORT}"
echo "==> Using CFE file: $${CFE_FILE}"

# Wait for BIG-IP CFE endpoint to be ready
echo "==> Waiting for BIG-IP CFE endpoint..."
for i in $(seq 1 30); do
  STATUS=$(curl -sku "$${BIGIP_USER}:$${BIGIP_PASS}" --connect-timeout 5 -o /dev/null -w "%%{http_code}" "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/shared/cloud-failover/info" 2>/dev/null || true)
  if [ "$${STATUS}" = "200" ]; then
    echo "==> BIG-IP CFE endpoint is ready"
    break
  fi
  echo "    Attempt $${i}/30 — waiting 10s..."
  sleep 10
done

# POST the CFE declaration
echo "==> Posting CFE declaration..."
RESPONSE=$(curl -sku "$${BIGIP_USER}:$${BIGIP_PASS}" \
  -X POST \
  -H "Content-Type: application/json" \
  -d @"$${CFE_FILE}" \
  -w "\n%%{http_code}" \
  "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/shared/cloud-failover/declare")

HTTP_CODE=$(echo "$${RESPONSE}" | tail -1)
BODY=$(echo "$${RESPONSE}" | awk 'NR>1{print prev} {prev=$$0}')

echo "==> Response code: $${HTTP_CODE}"
echo "$${BODY}" | python3 -m json.tool 2>/dev/null || echo "$${BODY}"

if [[ "$${HTTP_CODE}" =~ ^(200|202)$$ ]]; then
  echo "==> CFE declaration posted successfully to ${bigip_name}"
else
  echo "==> ERROR: CFE declaration failed with HTTP $${HTTP_CODE}"
  exit 1
fi
