#!/bin/bash
set -e

# Deploy Declarative Onboarding to BIG-IP ${bigip_name}
# Generated by Terraform — do not edit manually

BIGIP_HOST="${bigip_mgmt_ip}"
BIGIP_PORT="${bigip_mgmt_port}"
BIGIP_USER="${bigip_username}"
BIGIP_PASS=$(terraform output -raw ${bigip_password_output})
DO_FILE="$(dirname "$0")/${do_filename}"

echo "==> Deploying DO to ${bigip_name} at $${BIGIP_HOST}:$${BIGIP_PORT}"
echo "==> Using DO file: $${DO_FILE}"

# Wait for BIG-IP DO endpoint to be ready
echo "==> Waiting for BIG-IP management plane..."
for i in $(seq 1 30); do
  STATUS=$(curl -sku "$${BIGIP_USER}:$${BIGIP_PASS}" --connect-timeout 5 -o /dev/null -w "%%{http_code}" "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/shared/declarative-onboarding/info" 2>/dev/null || true)
  if [ "$${STATUS}" = "200" ]; then
    echo "==> BIG-IP DO endpoint is ready"
    break
  fi
  echo "    Attempt $${i}/30 — waiting 10s..."
  sleep 10
done

# POST the DO declaration
echo "==> Posting DO declaration..."
TMPFILE=$(mktemp)
HTTP_CODE=$(curl -sku "$${BIGIP_USER}:$${BIGIP_PASS}" \
  -X POST \
  -H "Content-Type: application/json" \
  -d @"$${DO_FILE}" \
  -o "$${TMPFILE}" \
  -w "%%{http_code}" \
  "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/shared/declarative-onboarding")

echo "==> Response code: $${HTTP_CODE}"
cat "$${TMPFILE}" | python3 -m json.tool 2>/dev/null || cat "$${TMPFILE}"
rm -f "$${TMPFILE}"

if [[ "$${HTTP_CODE}" =~ ^(200|202)$$ ]]; then
  echo "==> DO declaration posted successfully to ${bigip_name}"
else
  echo "==> ERROR: DO declaration failed with HTTP $${HTTP_CODE}"
  exit 1
fi
