# Deploy CFE declaration to BIG-IP ${bigip_name}
# Generated by Terraform — do not edit manually

$ErrorActionPreference = "Stop"

$BIGIP_HOST = "${bigip_mgmt_ip}"
$BIGIP_PORT = "${bigip_mgmt_port}"
$BIGIP_USER = "${bigip_username}"
$BIGIP_PASS = terraform output -raw ${bigip_password_output}
$CFE_FILE = Join-Path $PSScriptRoot "${cfe_filename}"

Write-Host "==> Deploying CFE to ${bigip_name} at $${BIGIP_HOST}:$${BIGIP_PORT}"
Write-Host "==> Using CFE file: $${CFE_FILE}"

# Create credential for basic auth
$SecPass = ConvertTo-SecureString $${BIGIP_PASS} -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PSCredential($${BIGIP_USER}, $SecPass)

# Wait for BIG-IP CFE endpoint to be ready
Write-Host "==> Waiting for BIG-IP CFE endpoint..."
for ($i = 1; $i -le 30; $i++) {
    try {
        $null = Invoke-WebRequest -Uri "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/shared/cloud-failover/info" `
            -Credential $Cred -SkipCertificateCheck -TimeoutSec 5 -ErrorAction Stop
        Write-Host "==> BIG-IP CFE endpoint is ready"
        break
    } catch {
        Write-Host "    Attempt $${i}/30 — waiting 10s..."
        Start-Sleep -Seconds 10
    }
}

# POST the CFE declaration
Write-Host "==> Posting CFE declaration..."
$Body = Get-Content -Raw $${CFE_FILE}

try {
    $Response = Invoke-RestMethod -Uri "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/shared/cloud-failover/declare" `
        -Method Post -Credential $Cred -SkipCertificateCheck `
        -ContentType "application/json" -Body $Body

    Write-Host "==> CFE declaration posted successfully to ${bigip_name}"
    $Response | ConvertTo-Json -Depth 10
} catch {
    $StatusCode = $_.Exception.Response.StatusCode.value__
    Write-Host "==> ERROR: CFE declaration failed with HTTP $${StatusCode}"
    Write-Host $_.Exception.Message
    exit 1
}
