# Force BIG-IP ${bigip_name} to standby (trigger failover)
# Generated by Terraform — do not edit manually

$ErrorActionPreference = "Stop"

$BIGIP_HOST = "${bigip_mgmt_ip}"
$BIGIP_PORT = "${bigip_mgmt_port}"
$BIGIP_USER = "${bigip_username}"
$BIGIP_PASS = terraform output -raw ${bigip_password_output}

Write-Host "==> Forcing ${bigip_name} to standby at $${BIGIP_HOST}:$${BIGIP_PORT}"

$SecPass = ConvertTo-SecureString $${BIGIP_PASS} -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PSCredential($${BIGIP_USER}, $SecPass)

$Body = '{"command":"run","utilCmdArgs":"-c \"tmsh run sys failover standby\""}'

try {
    $Response = Invoke-RestMethod -Uri "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/tm/util/bash" `
        -Method Post -Credential $Cred -SkipCertificateCheck `
        -ContentType "application/json" -Body $Body

    Write-Host "==> ${bigip_name} is now standby — failover triggered"
    $Response | ConvertTo-Json -Depth 10
} catch {
    $StatusCode = $_.Exception.Response.StatusCode.value__
    Write-Host "==> ERROR: Failover command failed with HTTP $${StatusCode}"
    Write-Host $_.Exception.Message
    exit 1
}
