#!/bin/bash
set -e

# Force BIG-IP ${bigip_name} to standby (trigger failover)
# Generated by Terraform — do not edit manually

BIGIP_HOST="${bigip_mgmt_ip}"
BIGIP_PORT="${bigip_mgmt_port}"
BIGIP_USER="${bigip_username}"
BIGIP_PASS=$(terraform output -raw ${bigip_password_output})

echo "==> Forcing ${bigip_name} to standby at $${BIGIP_HOST}:$${BIGIP_PORT}"

TMPFILE=$(mktemp)
HTTP_CODE=$(curl -sku "$${BIGIP_USER}:$${BIGIP_PASS}" \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"command":"run","utilCmdArgs":"-c \"tmsh run sys failover standby\""}' \
  -o "$${TMPFILE}" \
  -w "%%{http_code}" \
  "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/tm/util/bash")

echo "==> Response code: $${HTTP_CODE}"
cat "$${TMPFILE}" | python3 -m json.tool 2>/dev/null || cat "$${TMPFILE}"
rm -f "$${TMPFILE}"

if [ "$${HTTP_CODE}" = "200" ]; then
  echo "==> ${bigip_name} is now standby — failover triggered"
else
  echo "==> ERROR: Failover command failed with HTTP $${HTTP_CODE}"
  exit 1
fi
