#!/bin/bash
set -e

# Fix Azure management routes on BIG-IP ${bigip_name}
# Ensures routes to Azure DNS (168.63.129.16) and IMDS (169.254.169.254) exist via mgmt interface
# Generated by Terraform — do not edit manually

BIGIP_HOST="${bigip_mgmt_ip}"
BIGIP_PORT="${bigip_mgmt_port}"
BIGIP_USER="${bigip_username}"
BIGIP_PASS=$(terraform output -raw ${bigip_password_output})

echo "==> Fixing management routes on ${bigip_name} at $${BIGIP_HOST}:$${BIGIP_PORT}"

# The tmsh commands:
# 1. Get the default mgmt route gateway
# 2. Create azure_dns route (168.63.129.16/32) if missing
# 3. Create azure_metadata route (169.254.169.254/32) if missing
# 4. Save config
CMD="MGMT_GW=\$(tmsh list sys management-route default all-properties | grep -oE '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+'); tmsh list sys management-route | grep -q 168.63.129.16 || tmsh create sys management-route azure_dns network 168.63.129.16/32 gateway \$MGMT_GW; tmsh list sys management-route | grep -q 169.254.169.254 || tmsh create sys management-route azure_metadata network 169.254.169.254/32 gateway \$MGMT_GW; tmsh save sys config"

TMPFILE=$(mktemp)
HTTP_CODE=$(curl -sku "$${BIGIP_USER}:$${BIGIP_PASS}" \
  -X POST \
  -H "Content-Type: application/json" \
  -d "{\"command\":\"run\",\"utilCmdArgs\":\"-c '$${CMD}'\"}" \
  -o "$${TMPFILE}" \
  -w "%%{http_code}" \
  "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/tm/util/bash")

echo "==> Response code: $${HTTP_CODE}"
cat "$${TMPFILE}" | python3 -m json.tool 2>/dev/null || cat "$${TMPFILE}"
rm -f "$${TMPFILE}"

if [ "$${HTTP_CODE}" = "200" ]; then
  echo "==> Management routes verified/fixed on ${bigip_name}"
else
  echo "==> ERROR: Management route fix failed with HTTP $${HTTP_CODE}"
  exit 1
fi
