# Fix Azure management routes on BIG-IP ${bigip_name}
# Ensures routes to Azure DNS (168.63.129.16) and IMDS (169.254.169.254) exist via mgmt interface
# Generated by Terraform — do not edit manually

$ErrorActionPreference = "Stop"

$BIGIP_HOST = "${bigip_mgmt_ip}"
$BIGIP_PORT = "${bigip_mgmt_port}"
$BIGIP_USER = "${bigip_username}"
$BIGIP_PASS = terraform output -raw ${bigip_password_output}

Write-Host "==> Fixing management routes on ${bigip_name} at $${BIGIP_HOST}:$${BIGIP_PORT}"

$SecPass = ConvertTo-SecureString $${BIGIP_PASS} -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PSCredential($${BIGIP_USER}, $SecPass)

$Cmd = "MGMT_GW=`$(tmsh list sys management-route default all-properties | grep -oE '[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+'); tmsh list sys management-route | grep -q 168.63.129.16 || tmsh create sys management-route azure_dns network 168.63.129.16/32 gateway `$MGMT_GW; tmsh list sys management-route | grep -q 169.254.169.254 || tmsh create sys management-route azure_metadata network 169.254.169.254/32 gateway `$MGMT_GW; tmsh save sys config"
$Body = @{command = "run"; utilCmdArgs = "-c '$${Cmd}'"} | ConvertTo-Json

try {
    $Response = Invoke-RestMethod -Uri "https://$${BIGIP_HOST}:$${BIGIP_PORT}/mgmt/tm/util/bash" `
        -Method Post -Credential $Cred -SkipCertificateCheck `
        -ContentType "application/json" -Body $Body

    Write-Host "==> Management routes verified/fixed on ${bigip_name}"
    $Response | ConvertTo-Json -Depth 10
} catch {
    $StatusCode = $_.Exception.Response.StatusCode.value__
    Write-Host "==> ERROR: Management route fix failed with HTTP $${StatusCode}"
    Write-Host $_.Exception.Message
    exit 1
}
